name: discord_dart_bot
description: A discord bot to help our server.
version: 0.0.6
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-180.3.beta

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  nyxx: ^6.3.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
